/**
 * Autopilot executor — runs a saved CampaignTemplate on the user's behalf:
 * discovers companies, generates emails, and either drops them as READY drafts
 * for user review OR auto-sends them via Gmail.
 *
 * Call sites:
 *  - scripts/worker.ts   (cron-driven sweep)
 *  - server/routers/templates.ts  (manual "Run now")
 */
import type { CampaignTemplate } from '@prisma/client'
import { prisma } from './prisma'
import { discoverCompanies, generateEmail, type EmailTone, type CompanyResult } from './ai'
import { searchAllJobAPIs } from './job-apis'
import { resolveContactEmail, type ContactVerdict } from './contact-resolver'
import { estimateSalary } from './salary-estimator'
import { geocodeForwardBatch } from './geocode-cache'
import { sendGmailEmail, refreshAccessToken } from './gmail'
import { getTier, checkQuota, incrementUsage } from './entitlements'
import { logger } from './logger'

export type AutopilotFrequency = 'daily' | 'every2days' | 'weekly'

export interface AutopilotRunResult {
  runId: string
  status: 'SUCCESS' | 'FAILED' | 'SKIPPED'
  skipReason?: string
  discovered: number
  generated: number
  sent: number
  failed: number
  error?: string
}

const FREQUENCY_MS: Record<AutopilotFrequency, number> = {
  daily: 24 * 60 * 60 * 1000,
  every2days: 2 * 24 * 60 * 60 * 1000,
  weekly: 7 * 24 * 60 * 60 * 1000,
}

export function computeNextRunAt(frequency: string, from: Date = new Date()): Date {
  const ms = FREQUENCY_MS[(frequency as AutopilotFrequency)] ?? FREQUENCY_MS.daily
  return new Date(from.getTime() + ms)
}

/**
 * Ensures a single long-running campaign exists for this template; returns its id.
 * All autopilot-generated emails are grouped into this campaign so the user sees
 * them as one evolving outreach stream.
 */
async function ensureAutopilotCampaign(template: CampaignTemplate): Promise<string> {
  if (template.autopilotCampaignId) {
    const existing = await prisma.campaign.findFirst({
      where: { id: template.autopilotCampaignId, userId: template.userId },
      select: { id: true },
    })
    if (existing) return existing.id
  }

  const campaign = await prisma.campaign.create({
    data: {
      userId: template.userId,
      name: `Autopilot: ${template.name}`,
      description: `Auto-generated by autopilot template "${template.name}".`,
      status: 'ACTIVE',
      jobTitle: template.jobTitle ?? undefined,
      useEmailTemplate: template.useEmailTemplate,
      followUpEnabled: template.followUpEnabled,
      followUpDelayDays: template.followUpDelayDays,
      maxFollowUps: template.maxFollowUps,
      abTestEnabled: false, // keep autopilot simple — no A/B for now
      attachCv: template.attachCv,
    },
  })

  await prisma.campaignTemplate.update({
    where: { id: template.id },
    data: { autopilotCampaignId: campaign.id },
  })

  return campaign.id
}

async function getValidGmailAccessToken(userId: string): Promise<string | null> {
  const token = await prisma.gmailToken.findUnique({ where: { userId } })
  if (!token) return null

  const isExpired = token.expiresAt && new Date() > new Date(token.expiresAt.getTime() - 60_000)
  if (!isExpired) return token.accessToken
  if (!token.refreshToken) return null

  const refreshed = await refreshAccessToken(token.refreshToken)
  await prisma.gmailToken.update({
    where: { userId },
    data: {
      accessToken: refreshed.accessToken,
      refreshToken: refreshed.refreshToken ?? token.refreshToken,
      expiresAt: refreshed.expiresAt,
    },
  })
  return refreshed.accessToken
}

async function finishRun(
  runId: string,
  patch: Partial<{
    status: string
    skipReason: string | null
    discovered: number
    generated: number
    sent: number
    failed: number
    error: string | null
  }>,
): Promise<void> {
  await prisma.autopilotRun.update({
    where: { id: runId },
    data: { ...patch, finishedAt: new Date() },
  })
}

export async function runAutopilotForTemplate(templateId: string): Promise<AutopilotRunResult> {
  const template = await prisma.campaignTemplate.findUnique({ where: { id: templateId } })
  if (!template) {
    return { runId: '', status: 'FAILED', discovered: 0, generated: 0, sent: 0, failed: 0, error: 'template_not_found' }
  }

  const run = await prisma.autopilotRun.create({
    data: { templateId: template.id, status: 'RUNNING' },
  })

  const updateTemplateAfter = async () => {
    await prisma.campaignTemplate.update({
      where: { id: template.id },
      data: {
        autopilotLastRunAt: new Date(),
        autopilotNextRunAt: computeNextRunAt(template.autopilotFrequency),
      },
    })
  }

  const skip = async (reason: string): Promise<AutopilotRunResult> => {
    await finishRun(run.id, { status: 'SKIPPED', skipReason: reason })
    await updateTemplateAfter()
    logger.info({ templateId, reason }, 'autopilot: skipped')
    return { runId: run.id, status: 'SKIPPED', skipReason: reason, discovered: 0, generated: 0, sent: 0, failed: 0 }
  }

  try {
    // 1. Safety gates
    if (!process.env.AUTOPILOT_ENABLED || process.env.AUTOPILOT_ENABLED === 'false') {
      return await skip('autopilot_disabled_globally')
    }
    if (!template.autopilotEnabled) return await skip('template_disabled')
    if (!template.autopilotAcceptedAt) return await skip('no_consent')

    const tier = await getTier(template.userId)
    if (tier !== 'PRO') return await skip('not_pro')

    if (!template.jobTitle || !template.region) return await skip('missing_search_params')

    const profile = await prisma.userProfile.findUnique({ where: { userId: template.userId } })
    if (!profile?.cvText) return await skip('no_cv')

    // Gmail only strictly needed when auto-sending (requireApproval=false)
    let accessToken: string | null = null
    if (!template.autopilotRequireApproval) {
      accessToken = await getValidGmailAccessToken(template.userId)
      if (!accessToken) return await skip('no_gmail')
    }

    // 2. Quota gates
    const discoveryQuota = await checkQuota(template.userId, 'discovery')
    if (!discoveryQuota.allowed) return await skip('discovery_quota')

    const estimatedAi = Math.max(1, template.autopilotDailyCap)
    const aiQuota = await checkQuota(template.userId, 'ai_generation', estimatedAi)
    if (!aiQuota.allowed) return await skip('ai_quota')

    // Hunter monthly cap — skip the whole run if we're out of verification
    // credits rather than run a half-verified cycle.
    const hunterQuota = await checkQuota(template.userId, 'hunter_request')
    if (!hunterQuota.allowed) return await skip('hunter_quota')

    if (!template.autopilotRequireApproval) {
      const sendQuota = await checkQuota(template.userId, 'email_sent', estimatedAi)
      if (!sendQuota.allowed) return await skip('send_quota')
    }

    // 3. Campaign
    const campaignId = await ensureAutopilotCampaign(template)

    // 4. Discovery
    const searchMode = (template.searchMode as 'all' | 'top10' | 'best3') ?? 'top10'
    const dataSource = template.dataSource ?? 'both'

    let companies: CompanyResult[] = []
    try {
      if (dataSource === 'ai') {
        companies = await discoverCompanies({
          jobTitle: template.jobTitle,
          industry: template.industry ?? '',
          region: template.region,
          searchMode,
          userId: template.userId,
        })
      } else if (dataSource === 'jobs') {
        companies = await searchAllJobAPIs(template.jobTitle, template.region, searchMode)
      } else {
        const [ai, jobs] = await Promise.all([
          discoverCompanies({
            jobTitle: template.jobTitle,
            industry: template.industry ?? '',
            region: template.region,
            searchMode,
            userId: template.userId,
          }),
          searchAllJobAPIs(template.jobTitle, template.region, searchMode),
        ])
        const seen = new Set<string>()
        companies = [...jobs, ...ai].filter((c) => {
          const key = c.name.toLowerCase().trim()
          if (seen.has(key)) return false
          seen.add(key)
          return true
        })
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'discovery_failed'
      await finishRun(run.id, { status: 'FAILED', error: msg })
      await updateTemplateAfter()
      logger.error({ err, templateId }, 'autopilot: discovery failed')
      return { runId: run.id, status: 'FAILED', discovered: 0, generated: 0, sent: 0, failed: 0, error: msg }
    }
    await incrementUsage(template.userId, 'discovery')

    const discoveredCount = companies.length

    // 5. Blacklist filter
    const blacklist = await prisma.blacklistedCompany.findMany({
      where: { userId: template.userId },
      select: { name: true, domain: true },
    })
    const blNames = new Set(blacklist.map((b) => b.name.toLowerCase()))
    const blDomains = new Set(blacklist.map((b) => b.domain?.toLowerCase()).filter(Boolean) as string[])
    companies = companies.filter((c) => {
      if (blNames.has(c.name.toLowerCase())) return false
      if (c.domain && blDomains.has(c.domain.toLowerCase())) return false
      return true
    })

    // 6. Dedup against already-contacted companies across all user's campaigns
    const previouslySent = await prisma.generatedEmail.findMany({
      where: {
        campaign: { userId: template.userId },
        status: { in: ['SENT', 'OPENED', 'REPLIED', 'READY'] },
      },
      select: { company: { select: { name: true, contactEmail: true } } },
    })
    const sentEmails = new Set(
      previouslySent.map((e) => e.company.contactEmail?.toLowerCase()).filter(Boolean) as string[],
    )
    const sentNames = new Set(previouslySent.map((e) => e.company.name.toLowerCase()))
    companies = companies.filter((c) => {
      if (sentNames.has(c.name.toLowerCase())) return false
      if (c.contactEmail && sentEmails.has(c.contactEmail.toLowerCase())) return false
      return true
    })

    // 7. Must have a contact email (we can't send blind)
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    companies = companies.filter((c) => c.contactEmail && emailRegex.test(c.contactEmail))

    // 8. Cap to the daily limit — verification happens after persistence
    // below, so we only spend Hunter quota on companies we might actually email.
    const batch = companies.slice(0, template.autopilotDailyCap)

    if (batch.length === 0) {
      await finishRun(run.id, {
        status: 'SUCCESS',
        discovered: discoveredCount,
        generated: 0,
        sent: 0,
        failed: 0,
      })
      await updateTemplateAfter()
      return { runId: run.id, status: 'SUCCESS', discovered: discoveredCount, generated: 0, sent: 0, failed: 0 }
    }

    // 9. Geocode in one batch
    const locationQueries = batch.map((c) => c.location ?? template.region!).filter(Boolean) as string[]
    const geoMap = locationQueries.length > 0 ? await geocodeForwardBatch(locationQueries) : new Map()
    const lookupGeo = (raw: string | null | undefined) => {
      if (!raw) return null
      const key = raw.toLowerCase().trim().replace(/\s+/g, ' ')
      return geoMap.get(key) ?? null
    }

    // 10. Persist Company rows (ignore dup names within the campaign)
    const companyNameToId = new Map<string, string>()
    for (const c of batch) {
      const geo = lookupGeo(c.location) ?? lookupGeo(template.region)
      try {
        const row = await prisma.company.create({
          data: {
            campaignId,
            name: c.name,
            domain: c.domain || undefined,
            industry: c.industry || undefined,
            size: c.size || undefined,
            description: `${c.description}\n\nMatch reason: ${c.matchReason}`,
            contactEmail: c.contactEmail || undefined,
            contactName: c.contactName || undefined,
            linkedIn: c.linkedIn || undefined,
            latitude: geo?.lat ?? null,
            longitude: geo?.lng ?? null,
            region: geo?.shortName ?? null,
            status: 'PENDING',
          },
        })
        companyNameToId.set(c.name, row.id)
      } catch (err) {
        logger.warn({ err, company: c.name, templateId }, 'autopilot: company insert failed')
      }
    }

    // 11. Verify deliverability for every persisted company. `resolveContactEmail`
    // writes its result back to the Company row so generation can simply skip
    // anything that isn't `verified_email`. Sequential on purpose — Hunter has a
    // low rate limit and we don't want to blow the daily budget in parallel.
    const verdictByCompanyId = new Map<string, ContactVerdict>()
    for (const [, companyId] of companyNameToId) {
      const row = await prisma.company.findUnique({
        where: { id: companyId },
        select: {
          id: true,
          contactEmail: true,
          contactEmailStatus: true,
          contactEmailScore: true,
          contactEmailVerifiedAt: true,
        },
      })
      if (!row) continue
      verdictByCompanyId.set(companyId, await resolveContactEmail(row, template.userId))
    }

    // 12. Generate + (optionally) send
    const signatureParts = [
      profile.signatureName ?? '',
      profile.signaturePhone ?? '',
      profile.signatureAddress ?? '',
    ].filter(Boolean)
    const signatureBlock = signatureParts.length > 0 ? `\n${signatureParts.join('\n')}` : ''
    const fromHeader = await (async () => {
      const u = await prisma.user.findUnique({
        where: { id: template.userId },
        select: { name: true, email: true },
      })
      return u?.name ? `${u.name} <${u.email}>` : u?.email ?? ''
    })()

    const tone = (template.autopilotTone as EmailTone) ?? 'balanced'
    let generated = 0
    let sent = 0
    let failed = 0

    for (const c of batch) {
      const companyId = companyNameToId.get(c.name)
      if (!companyId || !c.contactEmail) continue

      // Skip unverified — wasting AI + Gmail quota on bouncy emails damages
      // the user's sender reputation. The Company row is still persisted as a
      // record of what was discovered, even though we won't email it.
      const verdict = verdictByCompanyId.get(companyId)
      if (!verdict || verdict.kind !== 'verified_email') {
        logger.info(
          { templateId, companyId, verdictKind: verdict?.kind },
          'autopilot: skipping unverified email',
        )
        failed += 1
        continue
      }

      try {
        const email = await generateEmail({
          cvText: profile.cvText,
          jobTitle: template.jobTitle!,
          companyName: c.name,
          companyIndustry: c.industry ?? null,
          companyDescription: c.description ?? null,
          companySize: c.size ?? null,
          contactName: c.contactName ?? null,
          skills: profile.skills ?? [],
          tone,
          userId: template.userId,
        })
        const body = email.body + signatureBlock

        if (template.autopilotRequireApproval) {
          // Drop into user's inbox as a READY draft — they click send from dashboard
          await prisma.generatedEmail.create({
            data: {
              companyId,
              campaignId,
              subject: email.subject,
              body,
              status: 'READY',
            },
          })
          generated += 1
        } else {
          // Auto-send via Gmail
          const emailRow = await prisma.generatedEmail.create({
            data: {
              companyId,
              campaignId,
              subject: email.subject,
              body,
              status: 'DRAFT',
            },
          })
          try {
            const { messageId, threadId } = await sendGmailEmail({
              from: fromHeader,
              to: c.contactEmail,
              subject: email.subject,
              body,
              accessToken: accessToken!,
              emailId: emailRow.id,
            })
            await prisma.generatedEmail.update({
              where: { id: emailRow.id },
              data: {
                status: 'SENT',
                sentAt: new Date(),
                gmailMessageId: messageId,
                gmailThreadId: threadId,
              },
            })
            await prisma.company.update({
              where: { id: companyId },
              data: { status: 'EMAILED' },
            })
            await incrementUsage(template.userId, 'email_sent', 1)
            generated += 1
            sent += 1
          } catch (sendErr) {
            logger.error({ err: sendErr, companyId }, 'autopilot: send failed')
            failed += 1
            await prisma.generatedEmail.update({
              where: { id: emailRow.id },
              data: { status: 'READY' }, // fall back to draft so user can retry
            })
          }
        }
      } catch (genErr) {
        logger.error({ err: genErr, companyName: c.name, templateId }, 'autopilot: generation failed')
        failed += 1
      }
    }

    await incrementUsage(template.userId, 'ai_generation', generated)

    await finishRun(run.id, {
      status: 'SUCCESS',
      discovered: discoveredCount,
      generated,
      sent,
      failed,
    })
    await updateTemplateAfter()

    logger.info({ templateId, discovered: discoveredCount, generated, sent, failed }, 'autopilot: run complete')
    return { runId: run.id, status: 'SUCCESS', discovered: discoveredCount, generated, sent, failed }
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'unknown_error'
    await finishRun(run.id, { status: 'FAILED', error: msg })
    await updateTemplateAfter()
    logger.error({ err, templateId }, 'autopilot: run failed')
    return { runId: run.id, status: 'FAILED', discovered: 0, generated: 0, sent: 0, failed: 0, error: msg }
  }
}
